cron:
  build: .

  command: >
    sh -c "
      if [ -f /etc/tenant-cron/crontab ]; then
        crontab /etc/tenant-cron/crontab;
      fi;
      exec cron -f
    "

  volumes:
    - /var/www/html:/var/www/html
    - /etc/tenant-php/conf.d:/usr/local/etc/php/conf.d:ro
    - /etc/tenant-cron:/etc/tenant-cron

  depends_on:
    - mariadb
    - redis
    - memcached

  restart: unless-stopped